name: Deploy to Google App Engine
on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed
jobs:
  build:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Create build
        run: npm run build
      - uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.gcp_credentials }}
          version: ${{ github.run_id }}